apiVersion: apps/v1
kind: Deployment
metadata:
  name: %name%
spec:
  replicas: 1
  selector:
    matchLabels:
      app: %name%
  template:
    metadata:
      labels:
        app: %name%
    spec:
      containers:
        - env:
          image: %image%
          name: %name%
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: %name%-svc
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: %name%