apiVersion: apps/v1
kind: Deployment
metadata:
  name: %name%
spec:
  replicas: 1
  selector:
    matchLabels:
      app: %name%
  template:
    metadata:
      labels:
        app: %name%
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: %db%
            - name: POSTGRES_PASSWORD
              value: %password%
            - name: POSTGRES_USER
              value: %user%
          image: postgres:13.0
          name: %name%
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: %name%
spec:
  ports:
    - name: "postgres"
      port: 5432
      targetPort: 5432
  selector:
    app: %name%