apiVersion: apps/v1
kind: Deployment
metadata:
  name: leocloud-beeyond-frontend
spec:
  selector:
    matchLabels:
      app: leocloud-beeyond-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: leocloud-beeyond-frontend
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
        - env:
            - name: API_URL
              value: https://student.cloud.htl-leonding.ac.at/{{ .Values.username }}/beeyond-backend
            - name: BASE_PATH
              value: /{{ .Values.username }}/beeyond
          name: leocloud-beeyond-frontend
          image: ghcr.io/htl-leonding-project/leocloud-beeyond-frontend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: leocloud-beeyond-frontend-svc
spec:
  selector:
    app: leocloud-beeyond-frontend
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: leocloud-beeyond-frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: student.cloud.htl-leonding.ac.at
      http:
        paths:
          - path: /{{ .Values.username }}/beeyond(/|$)(.*)$
            pathType: Prefix
            backend:
              service:
                name: leocloud-beeyond-frontend-svc
                port:
                  number: 80