/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        light: {
          ...require("daisyui/src/colors/themes")["[data-theme=light]"],
          "#2A2636primary": "#7e4eac",
          "secondary": "#e6d7ff",
          "base-100": "#ffffff",
          "base-200": "#f9fafb",
        },
        dark: {
          ...require("daisyui/src/colors/themes")["[data-theme=dark]"],
          "primary": "#7e4eac",
          "secondary": "#e6d7ff",
        },
        orange: {
          "primary": "#f79f65",
          "secondary": "#efb99b",
          "accent": "#ebed71",
          "neutral": "#2A2636",
          "base-100": "#282a36",
          "info": "#90CCE4",
          "success": "#0E5D43",
          "warning": "#F7AD5E",
          "error": "#FA7A6B",
        },
        fieryocean: {
          "primary": "#e85e4c",
          "secondary": "#72dbc0",
          "accent": "#f99461",
          "neutral": "#1C1B28",
          "base-100": "#282a36",
          "info": "#39A3C6",
          "success": "#1C8274",
          "warning": "#9C5402",
          "error": "#FA7A6B",
        },
      },
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
    ],
  },
};
