name: GitHub Pages CD

on:
  push:
    branches:
      - '*'
    paths:
      - docs/**
  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup asciidoctor
        run: sudo apt-get install -y asciidoctor
      - name: Setup asciidoctor-diagram
        run: sudo gem install asciidoctor-diagram
      - name: Setup graphviz
        run: sudo apt install graphviz
      - name: Make build script executable
        run: chmod +x docs/build
      - name: Build documentation
        run: docs/build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
