name: 🚀 Leocloud Deployment

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - 'CD backend'
      - 'CD frontend'
    types:
      - completed

env:
  HELM_RELEASE_NAME: leocloud-beeyond
  DEPLOYMENT_NAME: leocloud-beeyond
  NAMESPACE: student-m-remplbauer

jobs:
  deploy:
    name: 🚀 Deploy to Leocloud
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.25.4'

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.10.2'

      - name: Install oidc plugin for kubectl
        run: |
          wget https://github.com/int128/kubelogin/releases/download/v1.25.3/kubelogin_linux_amd64.zip
          mkdir kubelogin
          unzip kubelogin_linux_amd64.zip -d kubelogin
          mv kubelogin/kubelogin kubelogin/kubectl-oidc_login
          echo $(pwd)/kubelogin >> $GITHUB_PATH

      - uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Upgrade Helm Deployment
        run: helm upgrade --install ${{ env.HELM_RELEASE_NAME }} ./helm --namespace ${{ env.NAMESPACE }}